services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - '8085:8080'
    volumes:
      - /DATA/AppData/stirling-data:/configs
    restart: unless-stopped