services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /DATA/Media/music:/downloads/music
      - /DATA/Media/video:/downloads/video

  downtify:
    image: ghcr.io/henriquesebastiao/downtify:latest
    container_name: downtify
    restart: unless-stopped
    ports:
      - "8083:8000"
    volumes:
      - /DATA/Media/music:/downloads
      - /DATA/Media/config/downtify:/data

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8084:8096"
    volumes:
      - /DATA/Media/config/jellyfin:/config
      - /DATA/Media/music:/library/music
      - /DATA/Media/video:/library/video
      
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:latest
    container_name: swingmusic
    restart: unless-stopped
    ports:
      - "8082:1970"
    volumes:
      - /DATA/Media/music:/music
      - /DATA/Media/config/swingmusic:/config
    environment:
      - SWINGMUSIC_PORT=1970
      - SWINGMUSIC_DEVICE_NAME=oxidilily-swingmusic